version: '3.8'

services:
  postgres:
    container_name: postgres_dev
    image: postgres:alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  clickhouse:
    container_name: clickhouse_dev
    image: clickhouse/clickhouse-server:latest
    environment:
      CLICKHOUSE_USER: test
      CLICKHOUSE_PASSWORD: test
    ports:
      - "8123:8123"
      - "8124:9000"
    tmpfs:
      - /var/lib/clickhouse

  minio:
    container_name: minio_dev
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: supersecretpassword
    tmpfs:
      - /data
    command: server /data --console-address ':7070'

  rabbitmq:
    container_name: rabbitmq_dev
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
