version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - predeclared
    - staticcheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - varnamelen
    - wastedassign
    - whitespace
  disable:
    - depguard
    - funlen
    - gochecknoinits
    - gomodguard
    - interfacebloat
    - ireturn
    - mnd
    - nolintlint
    - paralleltest
    - prealloc
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - tparallel
    - wrapcheck
    - wsl
    - revive
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    forbidigo:
      forbid:
        - pattern: ^fmt.Print(f|ln)?$
        - pattern: ^log.(Panic|Fatal|Print)(f|ln)?$
        - pattern: ^os.Exit$
        - pattern: ^panic$
        - pattern: ^print(ln)?$
    gomodguard:
      blocked:
        modules:
          - github.com/pkg/errors:
              recommendations:
                - errors
    govet:
      enable:
        - shadow
        - fieldalignment
    misspell:
      locale: US
    varnamelen:
      max-distance: 12
      min-name-length: 2
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-decls:
        - i int
        - n int
        - w io.Writer
        - r io.Reader
        - b []byte
  exclusions:
    generated: lax
    rules:
      - linters:
          - forbidigo
          - gocognit
        path: (examples|main\.go|_test\.go)
      - linters:
          - forbidigo
        path: cmd
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
